#!/usr/bin/env bash
# Copyright 2025-2026 : Nawa Manusitthipol
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.

set -Eeuo pipefail
trap 'echo "❌ Error on line $LINENO"; exit 1' ERR

# --------------------------
# Root setup
# --------------------------
[ "$EUID" -eq 0 ] || { echo "❌ Run as root (use sudo)"; exit 1; }

# This script will always be installed by root.
HOME=/root


# --- Defaults ---
LEVEL=40                          # Early - before language setups so proxy is ready

STARTUP_FILE="/usr/share/startup.d/${LEVEL}-cb-network-whitelist--startup.sh"
PROFILE_FILE="/etc/profile.d/${LEVEL}-cb-network-whitelist--profile.sh"

# Utility commands
WHITELIST_ADD_CMD="/usr/local/bin/network-whitelist-add"
WHITELIST_LIST_CMD="/usr/local/bin/network-whitelist-list"
WHITELIST_RELOAD_CMD="/usr/local/bin/network-whitelist-reload"
WHITELIST_STATUS_CMD="/usr/local/bin/network-whitelist-status"

# Config locations
TINYPROXY_CONF="/etc/tinyproxy/tinyproxy.conf"
TINYPROXY_FILTER="/etc/tinyproxy/whitelist.txt"
DEFAULT_WHITELIST="/etc/tinyproxy/default-whitelist.txt"
USER_WHITELIST_NAME=".network-whitelist"

PROXY_PORT=18888

# ==== Things to do once at the call time by root. ====

# ---- Install tinyproxy ----
echo "📦 Installing tinyproxy..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y --no-install-recommends tinyproxy procps

# ---- Create default whitelist (common package registries) ----
echo "📝 Creating default whitelist..."
cat > "${DEFAULT_WHITELIST}" <<'WHITELIST_EOF'
# ============================================
# Default Network Whitelist for CodingBooth
# ============================================
# This file contains domains that are allowed
# through the network proxy by default.
# ============================================

# --- NPM / Node.js ---
registry.npmjs.org
npmjs.org
npmjs.com
yarnpkg.com
registry.yarnpkg.com
nodejs.org
unpkg.com

# --- Python / PyPI ---
pypi.org
pypi.python.org
files.pythonhosted.org
pythonhosted.org
python.org

# --- Maven / Java ---
repo.maven.apache.org
repo1.maven.org
central.maven.org
maven.org
jcenter.bintray.com
plugins.gradle.org
services.gradle.org
downloads.gradle-dn.com

# --- Go ---
proxy.golang.org
sum.golang.org
golang.org
go.dev
pkg.go.dev

# --- Rust / Cargo ---
crates.io
static.crates.io
index.crates.io
static.rust-lang.org

# --- Ruby / Gems ---
rubygems.org
api.rubygems.org

# --- PHP / Composer ---
packagist.org
repo.packagist.org
getcomposer.org

# --- Docker ---
registry-1.docker.io
docker.io
auth.docker.io
index.docker.io
hub.docker.com
production.cloudflare.docker.com

# --- GitHub ---
github.com
api.github.com
raw.githubusercontent.com
objects.githubusercontent.com
codeload.github.com
github-releases.githubusercontent.com
github-production-release-asset-*.s3.amazonaws.com

# --- GitLab ---
gitlab.com
registry.gitlab.com

# --- Common CDNs ---
cdn.jsdelivr.net
cdnjs.cloudflare.com
unpkg.com

# --- Ubuntu/Debian packages ---
archive.ubuntu.com
security.ubuntu.com
ppa.launchpad.net
deb.debian.org
security.debian.org

# --- Alpine packages ---
dl-cdn.alpinelinux.org

# --- VS Code extensions ---
marketplace.visualstudio.com
.*\.gallery\.vsassets\.io
update.code.visualstudio.com
vscode.blob.core.windows.net

# --- JetBrains ---
download.jetbrains.com
plugins.jetbrains.com
data.services.jetbrains.com

# --- Homebrew ---
brew.sh
formulae.brew.sh
ghcr.io

# --- Misc tools ---
astral.sh
get.docker.com
deno.land
bun.sh
WHITELIST_EOF
chmod 644 "${DEFAULT_WHITELIST}"

# ---- Configure tinyproxy ----
echo "⚙️  Configuring tinyproxy..."

# Backup original config
[ -f "${TINYPROXY_CONF}.orig" ] || cp "${TINYPROXY_CONF}" "${TINYPROXY_CONF}.orig"

cat > "${TINYPROXY_CONF}" <<EOF
# CodingBooth Network Whitelist Proxy Configuration
# Generated by network-whitelist--setup.sh

User tinyproxy
Group tinyproxy

Port ${PROXY_PORT}
Listen 127.0.0.1

Timeout 600
DefaultErrorFile "/usr/share/tinyproxy/default.html"
StatHost "tinyproxy.stats"
LogLevel Warning

MaxClients 100
MinSpareServers 2
MaxSpareServers 10
StartServers 5
MaxRequestsPerChild 0

# Whitelist filtering - only allow domains in the whitelist
Filter "${TINYPROXY_FILTER}"
FilterURLs Off
FilterExtended On
FilterCaseSensitive Off
FilterDefaultDeny Yes

# Allow connections from localhost only
Allow 127.0.0.1
Allow ::1

# Required headers
ViaProxyName "tinyproxy"

# Connection settings
ConnectPort 443
ConnectPort 563
ConnectPort 80
EOF
chmod 644 "${TINYPROXY_CONF}"

# ---- Create empty combined whitelist (will be populated at startup) ----
touch "${TINYPROXY_FILTER}"
chmod 644 "${TINYPROXY_FILTER}"

# ---- Create startup file: runs as normal user on container start ----
cat > "${STARTUP_FILE}" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

TINYPROXY_FILTER="/etc/tinyproxy/whitelist.txt"
DEFAULT_WHITELIST="/etc/tinyproxy/default-whitelist.txt"
USER_WHITELIST="$HOME/.network-whitelist"
PROXY_PORT=18888

# Network whitelist is always enabled when this setup is installed
echo "🔒 Setting up network whitelist proxy..."

# ============================================================================
# EXPERIMENTAL: iptables-based enforcement
# This prevents ACCIDENTAL bypassing of the proxy (e.g., scripts that don't
# respect HTTP_PROXY environment variables).
#
# WARNING: This is NOT a security boundary! A bad actor with shell access can:
#   - Modify iptables rules (if they have sudo)
#   - Kill tinyproxy and modify whitelist files
#   - Use other ports (8080, 8443, etc.)
#   - Use non-HTTP protocols (SSH tunnels, raw TCP)
#
# This feature provides defense-in-depth, not true isolation.
# Requires: --cap-add=NET_ADMIN in docker run args
# ============================================================================
if command -v iptables >/dev/null 2>&1; then
    # Check if we have CAP_NET_ADMIN (try a harmless iptables command)
    if sudo iptables -L OUTPUT -n >/dev/null 2>&1; then
        echo "🔥 Setting up iptables firewall rules (EXPERIMENTAL - not a security boundary)..."

        # Flush existing OUTPUT rules to start fresh
        sudo iptables -F OUTPUT 2>/dev/null || true

        # Allow all localhost traffic (proxy runs here)
        sudo iptables -A OUTPUT -o lo -j ACCEPT

        # Allow established connections (for proxy responses)
        sudo iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

        # Allow DNS (needed for domain resolution)
        sudo iptables -A OUTPUT -p udp --dport 53 -j ACCEPT
        sudo iptables -A OUTPUT -p tcp --dport 53 -j ACCEPT

        # Block direct HTTP/HTTPS - must go through proxy
        # NOTE: Only blocks ports 80/443. Other ports (8080, 8443, etc.) are NOT blocked.
        sudo iptables -A OUTPUT -p tcp --dport 80 -j REJECT --reject-with tcp-reset
        sudo iptables -A OUTPUT -p tcp --dport 443 -j REJECT --reject-with tcp-reset

        echo "✅ Firewall rules applied - direct HTTP/HTTPS on ports 80/443 blocked"
        echo "   (Note: This is experimental and can be bypassed by determined users)"
    else
        echo "ℹ️  No CAP_NET_ADMIN - firewall enforcement disabled"
        echo "   Add '--cap-add=NET_ADMIN' to run-args for experimental enforcement"
    fi
else
    echo "ℹ️  iptables not available - firewall enforcement disabled"
fi

# Combine default and user whitelists
{
    echo "# Combined whitelist - generated at startup"
    echo "# Do not edit directly - use network-whitelist-add or edit ~/.network-whitelist"
    echo ""

    # Default whitelist
    if [ -f "$DEFAULT_WHITELIST" ]; then
        echo "# === Default whitelist ==="
        grep -v '^\s*#' "$DEFAULT_WHITELIST" | grep -v '^\s*$' || true
    fi

    # User whitelist
    if [ -f "$USER_WHITELIST" ]; then
        echo ""
        echo "# === User whitelist ($USER_WHITELIST) ==="
        grep -v '^\s*#' "$USER_WHITELIST" | grep -v '^\s*$' || true
    fi
} | sort -u > "/tmp/whitelist.txt.tmp"

# Need sudo to update the filter file
sudo mv "/tmp/whitelist.txt.tmp" "${TINYPROXY_FILTER}"
sudo chmod 644 "${TINYPROXY_FILTER}"

# Start or reload tinyproxy
if pgrep -x tinyproxy > /dev/null 2>&1; then
    echo "🔄 Reloading tinyproxy..."
    sudo pkill -HUP tinyproxy || true
else
    echo "🚀 Starting tinyproxy..."
    sudo tinyproxy -c /etc/tinyproxy/tinyproxy.conf
fi

# Verify it's running
sleep 1
if pgrep -x tinyproxy > /dev/null 2>&1; then
    echo "✅ Network whitelist proxy is running on port ${PROXY_PORT}"
else
    echo "⚠️  Warning: tinyproxy may not have started correctly"
fi
EOF
chmod 755 "${STARTUP_FILE}"

# ---- Create profile file: sets proxy environment variables ----
cat > "${PROFILE_FILE}" <<'EOF'
# Profile: Network Whitelist Proxy
# Sets HTTP_PROXY/HTTPS_PROXY - always enabled when this setup is installed

PROXY_PORT=18888

export HTTP_PROXY="http://127.0.0.1:${PROXY_PORT}"
export HTTPS_PROXY="http://127.0.0.1:${PROXY_PORT}"
export http_proxy="http://127.0.0.1:${PROXY_PORT}"
export https_proxy="http://127.0.0.1:${PROXY_PORT}"

# NO_PROXY for localhost connections
export NO_PROXY="localhost,127.0.0.1,::1"
export no_proxy="localhost,127.0.0.1,::1"
EOF
chmod 644 "${PROFILE_FILE}"

# ---- Create utility: network-whitelist-add ----
cat > "${WHITELIST_ADD_CMD}" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

USER_WHITELIST="$HOME/.network-whitelist"

if [ $# -eq 0 ]; then
    echo "Usage: network-whitelist-add <domain> [domain2] ..."
    echo ""
    echo "Add domains to your personal network whitelist."
    echo "Changes take effect after running 'network-whitelist-reload'."
    echo ""
    echo "Examples:"
    echo "  network-whitelist-add example.com"
    echo "  network-whitelist-add api.example.com cdn.example.com"
    exit 1
fi

# Create user whitelist if it doesn't exist
if [ ! -f "$USER_WHITELIST" ]; then
    cat > "$USER_WHITELIST" <<'HEADER'
# Personal Network Whitelist
# Add one domain per line (wildcards supported: *.example.com)
# Lines starting with # are comments
# Run 'network-whitelist-reload' after editing

HEADER
fi

# Add each domain
for domain in "$@"; do
    # Check if already in whitelist
    if grep -qxF "$domain" "$USER_WHITELIST" 2>/dev/null; then
        echo "ℹ️  '$domain' is already in whitelist"
    else
        echo "$domain" >> "$USER_WHITELIST"
        echo "✅ Added '$domain' to whitelist"
    fi
done

echo ""
echo "Run 'network-whitelist-reload' to apply changes."
EOF
chmod 755 "${WHITELIST_ADD_CMD}"

# ---- Create utility: network-whitelist-list ----
cat > "${WHITELIST_LIST_CMD}" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

DEFAULT_WHITELIST="/etc/tinyproxy/default-whitelist.txt"
USER_WHITELIST="$HOME/.network-whitelist"
COMBINED_WHITELIST="/etc/tinyproxy/whitelist.txt"

show_help() {
    echo "Usage: network-whitelist-list [--default | --user | --combined | --all]"
    echo ""
    echo "Options:"
    echo "  --default   Show default whitelist (system-wide)"
    echo "  --user      Show your personal whitelist"
    echo "  --combined  Show the active combined whitelist"
    echo "  --all       Show all whitelists (default)"
    echo ""
}

show_file() {
    local file="$1"
    local label="$2"
    echo "=== $label ==="
    if [ -f "$file" ]; then
        cat "$file"
    else
        echo "(file does not exist)"
    fi
    echo ""
}

case "${1:-all}" in
    --help|-h)
        show_help
        ;;
    --default)
        show_file "$DEFAULT_WHITELIST" "Default Whitelist"
        ;;
    --user)
        show_file "$USER_WHITELIST" "User Whitelist (~/.network-whitelist)"
        ;;
    --combined)
        show_file "$COMBINED_WHITELIST" "Combined Active Whitelist"
        ;;
    --all|all)
        show_file "$DEFAULT_WHITELIST" "Default Whitelist"
        show_file "$USER_WHITELIST" "User Whitelist (~/.network-whitelist)"
        ;;
    *)
        echo "Unknown option: $1"
        show_help
        exit 1
        ;;
esac
EOF
chmod 755 "${WHITELIST_LIST_CMD}"

# ---- Create utility: network-whitelist-reload ----
cat > "${WHITELIST_RELOAD_CMD}" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

TINYPROXY_FILTER="/etc/tinyproxy/whitelist.txt"
DEFAULT_WHITELIST="/etc/tinyproxy/default-whitelist.txt"
USER_WHITELIST="$HOME/.network-whitelist"

echo "🔄 Reloading network whitelist..."

# Combine whitelists
{
    echo "# Combined whitelist - regenerated $(date)"
    echo ""

    if [ -f "$DEFAULT_WHITELIST" ]; then
        echo "# === Default whitelist ==="
        grep -v '^\s*#' "$DEFAULT_WHITELIST" | grep -v '^\s*$' || true
    fi

    if [ -f "$USER_WHITELIST" ]; then
        echo ""
        echo "# === User whitelist ==="
        grep -v '^\s*#' "$USER_WHITELIST" | grep -v '^\s*$' || true
    fi
} | sort -u > "/tmp/whitelist.txt.tmp"

sudo mv "/tmp/whitelist.txt.tmp" "${TINYPROXY_FILTER}"
sudo chmod 644 "${TINYPROXY_FILTER}"

# Reload tinyproxy
if pgrep -x tinyproxy > /dev/null 2>&1; then
    sudo pkill -HUP tinyproxy
    echo "✅ Whitelist reloaded and proxy signaled"
else
    echo "⚠️  Proxy not running. Starting it..."
    sudo tinyproxy -c /etc/tinyproxy/tinyproxy.conf
    echo "✅ Proxy started with new whitelist"
fi
EOF
chmod 755 "${WHITELIST_RELOAD_CMD}"

# ---- Create utility: network-whitelist-status ----
cat > "${WHITELIST_STATUS_CMD}" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

USER_WHITELIST="$HOME/.network-whitelist"
DEFAULT_WHITELIST="/etc/tinyproxy/default-whitelist.txt"
PROXY_PORT=18888

echo "=== Network Whitelist Status ==="
echo ""
echo "Status: ENABLED (always on when installed)"
echo ""

# Check proxy
if pgrep -x tinyproxy > /dev/null 2>&1; then
    echo "Proxy: Running (port ${PROXY_PORT})"
else
    echo "Proxy: NOT RUNNING"
    echo "  Run 'network-whitelist-reload' to start the proxy."
fi

echo ""

# Count domains
default_count=0
user_count=0
if [ -f "$DEFAULT_WHITELIST" ]; then
    default_count=$(grep -v '^\s*#' "$DEFAULT_WHITELIST" | grep -v '^\s*$' | wc -l || echo 0)
fi
if [ -f "$USER_WHITELIST" ]; then
    user_count=$(grep -v '^\s*#' "$USER_WHITELIST" | grep -v '^\s*$' | wc -l || echo 0)
fi

echo "Whitelisted domains:"
echo "  Default: ${default_count} domains"
echo "  User:    ${user_count} domains"
echo ""

# Show environment
echo "Environment:"
echo "  HTTP_PROXY:  ${HTTP_PROXY:-not set}"
echo "  HTTPS_PROXY: ${HTTPS_PROXY:-not set}"
echo ""
echo "Use 'network-whitelist-list' to see all whitelisted domains."
EOF
chmod 755 "${WHITELIST_STATUS_CMD}"

# Note: network-whitelist-enable and network-whitelist-disable are intentionally
# not provided. The whitelist is always enabled when this setup is installed.
# This prevents bad actors from simply disabling the security feature.

# ---- Allow coder user to manage tinyproxy via sudo without password ----
echo "🔐 Configuring sudo permissions for tinyproxy..."
cat > /etc/sudoers.d/tinyproxy-whitelist <<'EOF'
# Allow coder to manage tinyproxy for network whitelist
coder ALL=(ALL) NOPASSWD: /usr/bin/tinyproxy *
coder ALL=(ALL) NOPASSWD: /usr/bin/pkill -HUP tinyproxy
coder ALL=(ALL) NOPASSWD: /usr/bin/pkill tinyproxy
coder ALL=(ALL) NOPASSWD: /bin/mv /tmp/whitelist.txt.tmp /etc/tinyproxy/whitelist.txt
coder ALL=(ALL) NOPASSWD: /bin/chmod 644 /etc/tinyproxy/whitelist.txt
EOF
chmod 440 /etc/sudoers.d/tinyproxy-whitelist

echo ""
echo "✅ .... Network Whitelist is installed ...."
echo "• Startup file : ${STARTUP_FILE}"
echo "• Profile file : ${PROFILE_FILE}"
echo "• Default whitelist: ${DEFAULT_WHITELIST}"
echo "• User whitelist   : ~/.network-whitelist"
echo ""
echo "Commands:"
echo "  network-whitelist-status   - Show current status"
echo "  network-whitelist-list     - List whitelisted domains"
echo "  network-whitelist-add      - Add domain to user whitelist"
echo "  network-whitelist-reload   - Apply whitelist changes"
echo ""
echo "NOTE: Network whitelist is ALWAYS ENABLED when this setup is installed."
echo "      Internet access is restricted to whitelisted domains only."
echo ""
echo "To add custom domains, either:"
echo "  1. Run: network-whitelist-add example.com"
echo "  2. Edit: ~/.network-whitelist (one domain per line)"
echo "  3. For team defaults: add .booth/home/.network-whitelist to your repo"
echo ""
